# Generated by Django 6.0.7 on 2026-08-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chat.message'),
        ),
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('user_report', 'User submitted'), ('ai_safety_agent', 'AI-flagged (Safety agent)')], default='user_report', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL),
        ),
    ]
