# Generated by Django 6.0.7 on 2026-08-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetranslation',
            name='is_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
