# Generated by Django 5.2.16 on 2026-08-15 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyflag',
            name='blocked_text',
            field=models.TextField(blank=True, help_text='Snapshot of the message text. Only set for auto-blocked messages (where message is null) — otherwise the flagged content is recoverable via the message FK.', null=True),
        ),
        migrations.AddField(
            model_name='safetyflag',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Who sent the flagged content. Set directly rather than relying on message.sender, since message is null for auto-blocked content — this keeps admin actions (suspend/ban) working the same way for both cases.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safetyflag',
            name='message',
            field=models.ForeignKey(blank=True, help_text="Null when this flag came from an auto-blocked message — that message was never saved, so there's nothing to link to. See blocked_text for what was actually sent.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_flags', to='chat.message'),
        ),
    ]
