# Generated by Django 5.2.16 on 2026-08-16 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_safetyflag_blocked_text_safetyflag_user_and_more'),
        ('chat', '0001_initial'),
        ('social', '0002_like_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyflag',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='Set when the flagged content was a comment. Null when auto-blocked — the comment was never saved, see blocked_text instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_flags', to='social.comment'),
        ),
        migrations.AddField(
            model_name='safetyflag',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Set when the flagged content was a social post. Null when auto-blocked — the post was never saved, see blocked_text instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_flags', to='social.post'),
        ),
        migrations.AlterField(
            model_name='safetyflag',
            name='blocked_text',
            field=models.TextField(blank=True, help_text='Snapshot of the flagged text. Only set for auto-blocked content (where message/post/comment are all null) — otherwise the flagged content is recoverable via whichever FK is set.', null=True),
        ),
        migrations.AlterField(
            model_name='safetyflag',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Set when the flagged content was a chat message. Null when this flag came from an auto-blocked message — that message was never saved, see blocked_text instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_flags', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='safetyflag',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Who sent the flagged content. Set directly rather than relying on message.sender/post.user/comment.user, since those are all null for auto-blocked content — this keeps admin actions (suspend/ban) working the same way regardless of which content type was flagged.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_flags', to=settings.AUTH_USER_MODEL),
        ),
    ]
