# Generated by Django 6.0.7 on 2026-08-16 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0003_safetyflag_comment_safetyflag_post_and_more'),
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nudgelog',
            name='badge',
            field=models.ForeignKey(blank=True, help_text='Set when nudge_type is badge_progress. Exactly one of badge/mission must be set — enforced by the CheckConstraint below.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nudge_logs', to='engagement.badge'),
        ),
        migrations.AddField(
            model_name='nudgelog',
            name='mission',
            field=models.ForeignKey(blank=True, help_text='Set when nudge_type is mission_progress. Exactly one of badge/mission must be set — enforced by the CheckConstraint below.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nudge_logs', to='engagement.mission'),
        ),
        migrations.AddField(
            model_name='nudgelog',
            name='progress_pct',
            field=models.IntegerField(default=0, help_text='Progress (0-100) toward the badge/mission at the moment this nudge was sent. Used for delta-based rate-limiting — see ai_agents/services/nudge_service.py.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nudgelog',
            name='nudge_type',
            field=models.CharField(choices=[('badge_progress', 'Badge Progress'), ('mission_progress', 'Mission Progress')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='nudgelog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('badge__isnull', False), ('mission__isnull', True)), models.Q(('badge__isnull', True), ('mission__isnull', False)), _connector='OR'), name='nudgelog_exactly_one_of_badge_or_mission'),
        ),
    ]
