# Generated by Django 6.0.7 on 2026-08-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0004_nudgelog_badge_nudgelog_mission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nudgelog',
            name='was_dismissed',
        ),
    ]
