# Generated by Django 5.2.16 on 2026-08-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0005_remove_nudgelog_was_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='is_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
